### ISSUE TITLE
你好，我重写了一个界面，正在移植。您觉得怎么样呢？

### ISSUE THREAD

**Issue by LenmoisLemon** [blackboxo/CleanMyWechat#11]
[点我看图](https://pic.downk.cc/item/5eaa9bd7c2a9a83be53758d3.png)

**Comment by blackboxo** [comment]
> [点我看图](https://pic.downk.cc/item/5eaa9bd7c2a9a83be53758d3.png)

很不错呀，顺便有一些需求你想要一起实现下吗？
1. 自动识别出的多个微信，让用户选择哪几个账号的需要删除；
2. 有用户有每日定时删除的需求，可以考虑让应用开机自启动并常驻后台，或者“将选项变成参数加到快捷方式里运行自动执行”；
3. 还有一些小的需求，比如增加企业微信的支持 / Windows XP 系统的支持 / 增加应用打包后的签名等等；
非常感谢！

**Comment by LenmoisLemon** [comment]
不知道怎么回事，突然不行了？
我现在的版本是 2.9.0.114，提示扫不出来文件。
您方便排个错吗？

**Comment by blackboxo** [comment]
> 不知道怎么回事，突然不行了？
> 我现在的版本是 2.9.0.114，提示扫不出来文件。
> 您方便排个错吗？

您好，方便的话加我微信 blackboxo 交流吧，扫不出文件是指文件为 0 还是什么？

**Comment by LenmoisLemon** [comment]
是的，不过我有点怀疑是我自己的问题，刚刚在跑你的源码的时候报错：  
`FileNotFoundError: [Errno 2] No such file or directory: 'path_file.txt'  `
loadPath这个模块出的问题，然后我把它的第12行改成了
`if os.path.exists(filepath / 'path_file.txt'):`
就能运行了，但是手动输入目录就啥也扫不出来了。
（我是新装的微信，之前微信跑在沙盒里，下午你的源码我这里不改也能跑起来，我刚刚试的时候又不行了...）

**Comment by LenmoisLemon** [comment]
> > 是的，不过我有点怀疑是我自己的问题，刚刚在跑你的源码的时候报错：
> > `FileNotFoundError: [Errno 2] No such file or directory: 'path_file.txt' `
> > loadPath这个模块出的问题，然后我把它的第12行改成了
> > `if os.path.exists(filepath / 'path_file.txt'):`
> > 就能运行了，但是手动输入目录就啥也扫不出来了。
> > （我是新装的微信，之前微信跑在沙盒里，下午你的源码我这里不改也能跑起来，我刚刚试的时候又不行了...）
> 
> 这个应该是读取这个文件路径的关系。你把这个文件删掉，再跑一次，不然它直接读取这个文件里存储的路径。

成功！可是下一次运行的时候又会创建这个文件....
我再看看整个工作流程吧

**Comment by LenmoisLemon** [comment]
把loadPath第14行改成
`open(filepath, 'r') as f:`
貌似就可以了
这算是发现Bug一枚？ xd

**Comment by blackboxo** [comment]
> 貌似是计算文件是否需要删除的算法问题.... 有点伤脑筋啊（我不是专业搞这个的）
> 
> 在 autoui 这个模块这，343行改成：
> `if diff < month:`
> 
> Everything is fine....

这样把逻辑改错了呀。。  把少于这个月份的都删掉了

**Comment by LenmoisLemon** [comment]
整了半天想清楚了，文件是今天创建的，所以算不到之前，
电脑or文件改日期就能出现我预期的效果了。
简直智商下限..... 打扰了这么久

**Comment by blackboxo** [comment]
> 整了半天想清楚了，文件是今天创建的，所以算不到之前，
> 电脑or文件改日期就能出现我预期的效果了。
> 简直智商下限..... 打扰了这么久

没事，加油

**Comment by LenmoisLemon** [comment]
第一个需求实现了一下，但是还不完全... 我寻思fork一份，改动有点大....
第二个需求我寻思整个守护进程常驻，然后定时用命令行参数控制主程序行为就好了（可以搞个CleanMyWechat-Core这样的模块，把核心和GUI两边分开，既可以作为命令行程序，又可以作为模块导入GUI）
图标文件是从 iconfont 找的，希望能提供一个图标放在程序里

[Preview Here](https://pic.downk.cc/item/5eabac59c2a9a83be51893f8.png)

**Comment by blackboxo** [comment]
> 第一个需求实现了一下，但是还不完全... 我寻思fork一份，改动有点大....
> 第二个需求我寻思整个守护进程常驻，然后定时用命令行参数控制主程序行为就好了（可以搞个CleanMyWechat-Core这样的模块，把核心和GUI两边分开，既可以作为命令行程序，又可以作为模块导入GUI）
> 图标文件是从 iconfont 找的，希望能提供一个图标放在程序里
> 
> [Preview Here](https://pic.downk.cc/item/5eabac59c2a9a83be51893f8.png)

可以，之后发 PR 即可。

1. 第一个需求，应给用户提供一个不清除该账户的选项，同时针对每个账户，都可以定制时间和数据类型，以及， 自定义的路径应该和检测到的账户是同级的关系，可以考虑下如何排列合适。
2. 核心和 Core 分开的方法不错，我觉得可以这样做。
3. 图标我一会传上来。

**Comment by blackboxo** [comment]
> 第一个需求实现了一下，但是还不完全... 我寻思fork一份，改动有点大....
> 第二个需求我寻思整个守护进程常驻，然后定时用命令行参数控制主程序行为就好了（可以搞个CleanMyWechat-Core这样的模块，把核心和GUI两边分开，既可以作为命令行程序，又可以作为模块导入GUI）
> 图标文件是从 iconfont 找的，希望能提供一个图标放在程序里
> 
> [Preview Here](https://pic.downk.cc/item/5eabac59c2a9a83be51893f8.png)

你好，图标已上传，wechat.png

**Comment by LenmoisLemon** [comment]
折腾完配置系统了，写的非常烂（轻喷），后面再搞啥 core、守护、多目录存储就应该好办了，直接读配置应该就行

[预览配置页面](https://sbimg.cn/image/m2cH6)
[预览配置文件](https://sbimg.cn/image/m2RA7)

**Comment by LenmoisLemon** [comment]
[图挂了](https://i.loli.net/2020/05/01/dmtFAr7Cy5cIVbS.png)
[这张也是](https://i.loli.net/2020/05/01/G4tNVCbaW8rH7eE.png)

> 折腾完配置系统了，写的非常烂（轻喷），后面再搞啥 core、守护、多目录存储就应该好办了，直接读配置应该就行

**Comment by blackboxo** [comment]
> [图挂了](https://i.loli.net/2020/05/01/dmtFAr7Cy5cIVbS.png)
> [这张也是](https://i.loli.net/2020/05/01/G4tNVCbaW8rH7eE.png)
> 
> > 折腾完配置系统了，写的非常烂（轻喷），后面再搞啥 core、守护、多目录存储就应该好办了，直接读配置应该就行

nice  感觉很不错

**Comment by blackboxo** [comment]
你好，看了下你的 PR，有几个地方麻烦再完善一下

1. 整体窗口太小；
2. 三个按钮是什么意思需要注明，不然进去不理解如何操作；
3. 如果没有配置文件，可以在程序打开时直接跳出配置窗口；
4. 自定义路径的模块应该也是在下拉框中，例如下拉框最后一项是“自定义路径”，点击后出现输入路径的框；
5. 配置窗口的按钮，应该为“保存”，不使用“退出”；
6. 点击开始清除后，没有提示，需要等待很久才有进度条的反应，可以增加文字等提示。

**Comment by LenmoisLemon** [comment]
好的 第七条我的经验是不要打包成单文件 不然就会报错
窗口大小我这里感觉还正常 可能是因为我这分辨率比较低 我没有高分屏幕 不清楚到底是有多小 Qt Designer 里拖出来的貌似不能自动缩放 我去查查Qt文档看看有没有这样的功能

**Comment by blackboxo** [comment]
但是给用户使用，肯定是需要打包成单文件 exe

**Comment by blackboxo** [comment]
> 好的 第七条我的经验是不要打包成单文件 不然就会报错
> 窗口大小我这里感觉还正常 可能是因为我这分辨率比较低 我没有高分屏幕 不清楚到底是有多小 Qt Designer 里拖出来的貌似不能自动缩放 我去查查Qt文档看看有没有这样的功能

嗨，进展如何呀，有遇到什么问题吗

**Comment by LenmoisLemon** [comment]
sorry 最近事情比较多 功能上的特性没问题了 就是界面大小/单文件这方面比较麻烦... 稍后提交上来
窗口大小我看到有些软件在设置里提供了选项：大/中/小，我就按这个方向实现吧

**Comment by blackboxo** [comment]
> sorry 最近事情比较多 功能上的特性没问题了 就是界面大小/单文件这方面比较麻烦... 稍后提交上来
> 窗口大小我看到有些软件在设置里提供了选项：大/中/小，我就按这个方向实现吧

好的，单文件为什么报错的原因你了解吗

**Comment by LenmoisLemon** [comment]
> 好的，单文件为什么报错的原因你了解吗

用 pyinstaller 打包成单文件，保留命令行界面，在主程序运行的时候点开设置页面的时候报错，错误提示是找不到设置UI的 .py 源代码文件，而且报错的目录是系统临时文件目录。
（注意这里我是改了下逻辑的，不是现在在项目里那个，具体咋改的我也忘了，不过反正也不重要....）

我自己的分析：
主程序UI被打包成exe，而设置UI没有，于是主程序在调用设置页面UI（也就是 import）的时候，在程序工作的临时目录找不到 .py 文件，于是就会报错。

解决方法也很粗暴，复制粘贴到一个文件里打包再改改逻辑就好了，但是工作量稍微有点大。
两个页面其实很多方法是一样的，所以写一个 class 再继承、加载 .ui 布局文件就好。

**Comment by blackboxo** [comment]
> > 好的，单文件为什么报错的原因你了解吗
> 
> 用 pyinstaller 打包成单文件，保留命令行界面，在主程序运行的时候点开设置页面的时候报错，错误提示是找不到设置UI的 .py 源代码文件，而且报错的目录是系统临时文件目录。
> （注意这里我是改了下逻辑的，不是现在在项目里那个，具体咋改的我也忘了，不过反正也不重要....）
> 
> 我自己的分析：
> 主程序UI被打包成exe，而设置UI没有，于是主程序在调用设置页面UI（也就是 import）的时候，在程序工作的临时目录找不到 .py 文件，于是就会报错。
> 
> 解决方法也很粗暴，复制粘贴到一个文件里打包再改改逻辑就好了，但是工作量稍微有点大。
> 两个页面其实很多方法是一样的，所以写一个 class 再继承、加载 .ui 布局文件就好。

是不是打包的时候，要写命令把另一个py也打包进去

**Comment by blackboxo** [comment]
> sorry 最近事情比较多 功能上的特性没问题了 就是界面大小/单文件这方面比较麻烦... 稍后提交上来
> 窗口大小我看到有些软件在设置里提供了选项：大/中/小，我就按这个方向实现吧

我之前的版本没有用户反应窗口太小，我也是固定尺寸的

**Comment by LenmoisLemon** [comment]
稍微拉大了一点
[主页](https://i.loli.net/2020/05/15/hqQJW279nAuf5G4.jpg)
[设置](https://i.loli.net/2020/05/15/A57DbTinLUIBajw.jpg)

**Comment by blackboxo** [comment]
> 稍微拉大了一点
> [主页](https://i.loli.net/2020/05/15/hqQJW279nAuf5G4.jpg)
> [设置](https://i.loli.net/2020/05/15/A57DbTinLUIBajw.jpg)

发现奇怪的问题，我这边是没有对齐的，而且整体尺寸有些怪

**Comment by blackboxo** [comment]
> 稍微拉大了一点
> [主页](https://i.loli.net/2020/05/15/hqQJW279nAuf5G4.jpg)
> [设置](https://i.loli.net/2020/05/15/A57DbTinLUIBajw.jpg)

这个自定义选了文件夹之后，并没有变化

**Comment by LenmoisLemon** [comment]
自定义选文件夹必须是没有配置文件＋自动搜索不到微信目录才生效的，
控件错位是缩放问题，Windows 缩放比例调到 100％ 应该就没问题了（不过这太蛋疼了）

**Comment by blackboxo** [comment]
> 自定义选文件夹必须是没有配置文件＋自动搜索不到微信目录才生效的，
> 控件错位是缩放问题，Windows 缩放比例调到 100％ 应该就没问题了（不过这太蛋疼了）

自定义是否可以改成“+自定义”，然后点击选择路径之后，左侧下拉框增加”自定义路径1“，这样就可以增加多个自定义路径。

**Comment by LenmoisLemon** [comment]
桌面端好看点的应用现在都 Electron 统一天下了....
毕竟一堆开发好的东西堆在那，稍微改一改就能跑了，而且颜值都还不错。
还用 Qt 的一般都是技术栈离不开的项目 而且 Pyqt 还不是原生，用的人就更少了（悲）

**Comment by blackboxo** [comment]
> 桌面端好看点的应用现在都 Electron 统一天下了....
> 毕竟一堆开发好的东西堆在那，稍微改一改就能跑了，而且颜值都还不错。
> 还用 Qt 的一般都是技术栈离不开的项目 而且 Pyqt 还不是原生，用的人就更少了（悲）

早知道也用 Electron 了，我还是 js 熟悉点

**Comment by blackboxo** [comment]
剩下的问题还改嘛？

**Comment by blackboxo** [comment]
> 桌面端好看点的应用现在都 Electron 统一天下了....
> 毕竟一堆开发好的东西堆在那，稍微改一改就能跑了，而且颜值都还不错。
> 还用 Qt 的一般都是技术栈离不开的项目 而且 Pyqt 还不是原生，用的人就更少了（悲）

老哥还做嘛，剩下那点工作搞搞完？
