### ISSUE TITLE
这软件以前都没报毒，现在360开始报毒了

### ISSUE THREAD

**Issue by command200** [blackboxo/CleanMyWechat#15]
![image](https://user-images.githubusercontent.com/62540177/84001341-f6440f00-a998-11ea-811e-f5d8bbb9b44d.png)

**Comment by blackboxo** [comment]
尴尬，应该是误报吧，可以查看 https://blog.csdn.net/hfangliao/article/details/51868508
等下一版本我再送交各个杀毒软件进行测试

**Comment by command200** [comment]
期待下个版本，我也知道是误报，但我也不好推荐给别人用

**Comment by blackboxo** [comment]
> 期待下个版本，我也知道是误报，但我也不好推荐给别人用

感谢感谢  最近时间不多 尽快推出新版本
