### ISSUE TITLE
Win10下运行报错

### ISSUE THREAD

**Issue by jwhsir** [blackboxo/CleanMyWechat#16]
Win10下运行报错，并提示“Python”已停止工作

C:\Users\Thinkpad\Downloads\Compressed\CleanMyWechat-master>python autodelete.py
Traceback (most recent call last):
  File "C:\Users\Thinkpad\Downloads\Compressed\CleanMyWechat-master\autoui.py", line 229, in confirm
    self.videoCheck)
  File "C:\Users\Thinkpad\Downloads\Compressed\CleanMyWechat-master\autoui.py", line 272, in getFileNum
    dirname = PureWindowsPath(path)
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python36\lib\pathlib.py", line 624, in __new__
    return cls._from_parts(args)
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python36\lib\pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python36\lib\pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list

**Comment by blackboxo** [comment]
你是下的源码是吗，直接运行 ngui.py 文件

**Comment by jwhsir** [comment]
> 你是下的源码是吗，直接运行 ngui.py 文件

您好，感谢回复，成功运行了但还是有两个问题

1、仍有报错提示
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0

2、C:\Users\Thinkpad\Documents\WeChat Files\UserName\Data 这个文件夹占据了大量空间，这个文件夹的内容是可以删除的吗？网上说该文件夹内的dat文件主要是表情包。未来可以考虑加入删除这些内容的功能。

谢谢！

**Comment by blackboxo** [comment]
> > 你是下的源码是吗，直接运行 ngui.py 文件
> 
> 
> 
> 您好，感谢回复，我才发现原来已经有exe的程序了，还折腾了半天的Python... 
> 
> 
> 
> 是一个很好的工具，感谢开发者的付出，但还有这样一个问题：C:\Users\Thinkpad\Documents\WeChat Files\UserName\Data 这个文件夹占据了大量空间，这个文件夹的内容是可以删除的吗？网上说该文件夹内的dat文件主要是表情包。未来可以考虑加入删除这些内容的功能。
> 
> 
> 
> 谢谢！

这个文件夹好像有涉及到聊天记录？

**Comment by jwhsir** [comment]
> > > 你是下的源码是吗，直接运行 ngui.py 文件
> > 
> > 
> > 您好，感谢回复，我才发现原来已经有exe的程序了，还折腾了半天的Python...
> > 是一个很好的工具，感谢开发者的付出，但还有这样一个问题：C:\Users\Thinkpad\Documents\WeChat Files\UserName\Data 这个文件夹占据了大量空间，这个文件夹的内容是可以删除的吗？网上说该文件夹内的dat文件主要是表情包。未来可以考虑加入删除这些内容的功能。
> > 谢谢！
> 
> 这个文件夹好像有涉及到聊天记录？

手动删除了这个文件夹根目录下的dat文件（未删除子文件夹内的文件），暂时没有问题，聊天记录未丢失。可能有待未来进一步查证。感谢。
