### ISSUE TITLE
是否可以跟手机一样选择性的删除聊天

### ISSUE THREAD

**Issue by wangjian1119** [blackboxo/CleanMyWechat#17]
是否可以跟手机一样选择性的删除聊天

**Comment by blackboxo** [comment]
> 是否可以跟手机一样选择性的删除聊天

暂时没有发现办法，直接右键删除那个人的聊天可以吗？

**Comment by wangjian1119** [comment]
不好意思，上面说错了。
是否可以保留特定联系人的文件、图片、视频

**Comment by blackboxo** [comment]
> 不好意思，上面说错了。
> 是否可以保留特定联系人的文件、图片、视频

这个做不到，微信在存储的时候没有做区分

**Comment by wangjian1119** [comment]
好的，谢谢
