### ISSUE TITLE
请问UWP的地址在哪？

### ISSUE THREAD

**Issue by Kissky** [blackboxo/CleanMyWechat#29]
似乎不是WeChat Files文件，但程序又不识别我的微信垃圾或过时文件所在文件夹

**Comment by blackboxo** [comment]
C:\\Users\\' + user + '\\AppData\\Local\\Packages\\TencentWeChatLimited.WeChatUWP_sdtnhv12zgd7a\\LocalCache\\Roaming\\Tencent\\WeChatAppStore\\WeChatAppStore Files

**Comment by blackboxo** [comment]
记得勾选第一个选项
