### ISSUE TITLE
无法清除，始终提示没有需要清理的文件

### ISSUE THREAD

**Issue by CWZ7605** [blackboxo/CleanMyWechat#30]
我是用mklink功能，把D盘的wechat file映射到C盘的，然后打开软件，可以正常识别到我的账号。但是点清除就说没啥要清除的。我手动定位到D盘的WeChat file文件夹，也是一样的情况。

**Comment by blackboxo** [comment]
> 我是用mklink功能，把D盘的wechat file映射到C盘的，然后打开软件，可以正常识别到我的账号。但是点清除就说没啥要清除的。我手动定位到D盘的WeChat file文件夹，也是一样的情况。

有没有把第一个选项打勾呀？

**Comment by CWZ7605** [comment]
> 
> 
> > 我是用mklink功能，把D盘的wechat file映射到C盘的，然后打开软件，可以正常识别到我的账号。但是点清除就说没啥要清除的。我手动定位到D盘的WeChat file文件夹，也是一样的情况。
> 
> 有没有把第一个选项打勾呀？

😂是我草率了
