### ISSUE TITLE
没有需要清理的文件？

### ISSUE THREAD

**Issue by laycher** [blackboxo/CleanMyWechat#31]
使用2.0版本时候，选中了自己的微信号。
但是点击清理提示没有需要清理的文件。

明明有超过180天的数据啊。
![图片](https://user-images.githubusercontent.com/1949584/108792233-bf139d80-75bb-11eb-9bdd-97430ade33d2.png)

**Comment by blackboxo** [comment]
> 使用2.0版本时候，选中了自己的微信号。
> 但是点击清理提示没有需要清理的文件。
> 
> 明明有超过180天的数据啊。
> ![图片](https://user-images.githubusercontent.com/1949584/108792233-bf139d80-75bb-11eb-9bdd-97430ade33d2.png)

需要勾选第一个， 是否清理该账号

**Comment by bigcachetx** [comment]
这个勾选太多余了吧，上面不就是选择了这个账号么？建议下一版去掉

我的理解是删除这个账号的所有记录，不敢勾选。

**Comment by laycher** [comment]
> 
> 
> > 使用2.0版本时候，选中了自己的微信号。
> > 但是点击清理提示没有需要清理的文件。
> > 明明有超过180天的数据啊。
> > ![图片](https://user-images.githubusercontent.com/1949584/108792233-bf139d80-75bb-11eb-9bdd-97430ade33d2.png)
> 
> 需要勾选第一个， 是否清理该账号

我也同意楼上的说法，我也以为是“删除这个账号的所有记录”，搞的我不敢勾选。

而且我还想找这个勾选是什么意思，也没有找到相关说明。

建议去掉这个勾选得了，用这个就是为了清理账户了，怎么还要多选一次呢？

**Comment by blackboxo** [comment]
> > > 使用2.0版本时候，选中了自己的微信号。
> > > 但是点击清理提示没有需要清理的文件。
> > > 明明有超过180天的数据啊。
> > > ![图片](https://user-images.githubusercontent.com/1949584/108792233-bf139d80-75bb-11eb-9bdd-97430ade33d2.png)
> > 
> > 
> > 需要勾选第一个， 是否清理该账号
> 
> 我也同意楼上的说法，我也以为是“删除这个账号的所有记录”，搞的我不敢勾选。
> 
> 而且我还想找这个勾选是什么意思，也没有找到相关说明。
> 
> 建议去掉这个勾选得了，用这个就是为了清理账户了，怎么还要多选一次呢？

这是为了多个微信号的用户设计的，他一般只需要清除其中部分账户

**Comment by blackboxo** [comment]
> 这个勾选太多余了吧，上面不就是选择了这个账号么？建议下一版去掉
> 
> 我的理解是删除这个账号的所有记录，不敢勾选。

这是为了多个微信号的用户设计的，他一般只需要清除其中部分账户

**Comment by blackboxo** [comment]
这边确实可以更改一下设计，以免引起误解

**Comment by qa2080639** [comment]
> > > 使用2.0版本时候，选中了自己的微信号。
> > > 但是点击清理提示没有需要清理的文件。
> > > 明明有超过180天的数据啊。
> > > ![图片](https://user-images.githubusercontent.com/1949584/108792233-bf139d80-75bb-11eb-9bdd-97430ade33d2.png)
> > 
> > 
> > 需要勾选第一个， 是否清理该账号
> 
> 我也同意楼上的说法，我也以为是“删除这个账号的所有记录”，搞的我不敢勾选。
> 
> 而且我还想找这个勾选是什么意思，也没有找到相关说明。
> 
> 建议去掉这个勾选得了，用这个就是为了清理账户了，怎么还要多选一次呢？

我也以为是全部删除   这个选项才有歧义了   怪不得没有要删除的文件

**Comment by hus007** [comment]
> > 使用2.0版本时候，选中了自己的微信号。
> > 但是点击清理提示没有需要清理的文件。
> > 明明有超过180天的数据啊。
> > ![图片](https://user-images.githubusercontent.com/1949584/108792233-bf139d80-75bb-11eb-9bdd-97430ade33d2.png)
> 
> 需要勾选第一个， 是否清理该账号

我已经勾选了，为什么还是显示 没有需要清理的文件啊 :(
![image](https://user-images.githubusercontent.com/103224752/183303245-9b14ac22-2b0e-4dfa-a9ab-2af05581248c.png)

**Comment by blackboxo** [comment]
是不是没有 180 天以前的？

> > > 使用2.0版本时候，选中了自己的微信号。
> > > 但是点击清理提示没有需要清理的文件。
> > > 明明有超过180天的数据啊。
> > > ![图片](https://user-images.githubusercontent.com/1949584/108792233-bf139d80-75bb-11eb-9bdd-97430ade33d2.png)
> > 
> > 
> > 需要勾选第一个， 是否清理该账号
> 
> 我已经勾选了，为什么还是显示 没有需要清理的文件啊 :( ![image](https://user-images.githubusercontent.com/103224752/183303245-9b14ac22-2b0e-4dfa-a9ab-2af05581248c.png)

**Comment by hus007** [comment]
> 是不是没有 180 天以前的？
> 
> > > > 使用2.0版本时候，选中了自己的微信号。
> > > > 但是点击清理提示没有需要清理的文件。
> > > > 明明有超过180天的数据啊。
> > > > ![图片](https://user-images.githubusercontent.com/1949584/108792233-bf139d80-75bb-11eb-9bdd-97430ade33d2.png)
> > > 
> > > 
> > > 需要勾选第一个， 是否清理该账号
> > 
> > 
> > 我已经勾选了，为什么还是显示 没有需要清理的文件啊 :( ![image](https://user-images.githubusercontent.com/103224752/183303245-9b14ac22-2b0e-4dfa-a9ab-2af05581248c.png)

有的，不过不知道为什么这些文件夹里都没有内容。算了，谢谢大佬啦
![image](https://user-images.githubusercontent.com/103224752/184402934-1bf34dcb-1e18-4dac-a733-f57e2f43247a.png)

**Comment by blackboxo** [comment]
已更新 V2.1 版本，优化了该逻辑
