### ISSUE TITLE
显示清理失败，求解决

### ISSUE THREAD

**Issue by luo00537** [blackboxo/CleanMyWechat#34]
图床
https://imgtu.com/i/6mZtLq
https://imgtu.com/i/6mZUe0

**Comment by blackboxo** [comment]
请问是自定义的路径还是自动识别的？  以为微信是什么版本？

**Comment by luo00537** [comment]
@blackboxo 自动识别 最新版本

**Comment by blackboxo** [comment]
微信是从哪边下载的版本？

**Comment by luo00537** [comment]
@blackboxo 官网

**Comment by blackboxo** [comment]
理论上不应该呀，看下你的文件夹结构吧

**Comment by lazlo95152** [comment]
wxid和filestorage 2023了还是清理失败
https://imgse.com/i/p9frK0S
https://imgse.com/i/p9frum8

**Comment by lazlo95152** [comment]
wxid和filestorage 2023了还是清理失败
https://imgse.com/i/p9frum8
https://imgse.com/i/p9frK0S

**Comment by blackboxo** [comment]
😢 要不加我微信看看 blackboxo
