### ISSUE TITLE
清理掉的文件没有移到回收站而是直接删除了

### ISSUE THREAD

**Issue by Sunmoone** [blackboxo/CleanMyWechat#39]
自定义的微信文件路径，清理进度到100后提示文件移动到回收站，可以进行确认删除。
但是到回收站里只看到video和image的相关文件夹，其他文件则没有出现在回收站

**Comment by blackboxo** [comment]
应该不会，是不是其他文件不符合条件，并没有删除？

**Comment by blackboxo** [comment]
需要删除的文件类型需要进行勾选
