### ISSUE TITLE
无法清理

### ISSUE THREAD

**Issue by eatWh** [blackboxo/CleanMyWechat#41]
明明有微信缓存，为啥设置好后会显示当前无东西可清理？

**Comment by tttfffyyy** [comment]
是不支持新版微信吗

**Comment by blackboxo** [comment]
> 明明有微信缓存，为啥设置好后会显示当前无东西可清理？

有没有勾选第一个选项呢？

**Comment by tttfffyyy** [comment]
> > 明明有微信缓存，为啥设置好后会显示当前无东西可清理？
> 
> 有没有勾选第一个选项呢？

感谢提醒，误以为第一个选项是删除账号，没问题了
