### ISSUE TITLE
配置好路径点击开始没有反应呢

### ISSUE THREAD

**Issue by topkof** [blackboxo/CleanMyWechat#42]
2.0之前的版本用过是好用的，现在以管理员身份运行点击开始也没反应~

**Comment by blackboxo** [comment]
> 2.0之前的版本用过是好用的，现在以管理员身份运行点击开始也没反应~

没反应是指说没有可清理的，还是没出现东西？（后者可能是文件太多，需要查询很久，多等一会就会开始了）

**Comment by topkof** [comment]
无论账号文件夹内文件多或小(删除多久以前的文件改成0或1)，点击开始没有运行迹象，进程没有CPU消耗，也没有读取磁盘

**Comment by blackboxo** [comment]
需要勾选第一个选项，你勾选了嘛

**Comment by montella11** [comment]
勾选了也没有反应，显示无需清理，明明有啊

**Comment by blackboxo** [comment]
🤔 理论上不应该呀
