### ISSUE TITLE
提示“没有需要清理的文件”

### ISSUE THREAD

**Issue by ReturnAc** [blackboxo/CleanMyWechat#43]
微信版本：3.4.5.27
使用2.0版本清理，加载配置文件成功，保存后返回主界面点开始，提示“没有需要清理的文件”
![image](https://user-images.githubusercontent.com/26931645/146292051-634c8d20-6006-4bf7-bf82-ceef5f96e64f.png)

![image](https://user-images.githubusercontent.com/26931645/146292232-80eb5912-df0a-4b5a-95d9-ec66cd614695.png)

**Comment by blackboxo** [comment]
你这边确实没有 365 天前的数据呢

**Comment by ReturnAc** [comment]
> 

原来如此！已经可以了，谢谢！
