### ISSUE TITLE
Adding this software to scoop buckets

### ISSUE THREAD

**Issue by AkariiinMKII** [blackboxo/CleanMyWechat#49]
[Scoop](https://github.com/ScoopInstaller/Scoop) is a command-line installer for Windows.
[Under construction](https://github.com/chawyehsu/dorado/pull/583) now :P, how about selecting an open source license?

**Comment by AkariiinMKII** [comment]
顺带问一下目前只支持Windows x64吗

**Comment by blackboxo** [comment]
> 顺带问一下目前只支持Windows x64吗

没有测试过 32 位，可能不支持

**Comment by blackboxo** [comment]
> [Scoop](https://github.com/ScoopInstaller/Scoop) is a command-line installer for Windows. [Under construction](https://github.com/chawyehsu/dorado/pull/583) now :P, how about selecting an open source license?

okay. Add MIT license.
