### ISSUE TITLE
该更新了，新版本失效

### ISSUE THREAD

**Issue by L-JH** [blackboxo/CleanMyWechat#51]

**Comment by blackboxo** [comment]
请问什么环境下失效？

**Comment by busiqiao** [comment]
闪退了，怎么回事

**Comment by blackboxo** [comment]
> 闪退了，怎么回事

可能是文件太多，建议先把时间设置久一点

**Comment by busiqiao** [comment]
> > 闪退了，怎么回事
> 
> 可能是文件太多，建议先把时间设置久一点
>设置了时间，刚开始提示没有需要清理的文件，再重新打开设置的时候就会闪退，我看了一下json文件里面是空的
<img width="284" alt="屏幕截图 2022-05-23 134132" src="https://user-images.githubusercontent.com/61554653/169751092-7091383a-4e1c-412b-a9d1-df549cbe9b17.png">

**Comment by busiqiao** [comment]
>发现问题了，保存微信文件的路径更改了，所以得到了空的json文件，闪退可能是程序没有处理空配置文件的方法吧

**Comment by blackboxo** [comment]
#48
