### ISSUE TITLE
可以增加一个删除的文件预览吗？

### ISSUE THREAD

**Issue by ayuayue** [blackboxo/CleanMyWechat#58]
有很多文件想要删除，但是害怕会删除一些重要的问题，都放到回收站一个一个还原太繁琐，可以清理之前预览被清理的问题吗，可以单选多选，选中的才删除。

**Comment by blackboxo** [comment]
删除的文件很多，暂时没有想到合适的预览方式

**Comment by David-hose** [comment]
可以参考一下微信客户端里面，存储空间管理的界面。进行分类有选择性的删除。通常情况下需要删除的更多是公众号和群聊的信息。针对这些的话是不是可以标记出来群名称、公众号的名称。在选择性删除的时候可以更加清晰。与个人的聊天记录的话可以按照文件类型进行分类，主要删除聊天中的哪些大的视频，图片啥的。

**Comment by blackboxo** [comment]
我们从文件夹好像无法直接区分群聊和单聊

**Comment by ayuayue** [comment]
找到了一个删除重复文件并可以添加链接的，https://github.com/arsenetar/dupeguru
