### ISSUE TITLE
下载后无法启动安装

### ISSUE THREAD

**Issue by foredoom007** [blackboxo/CleanMyWechat#61]
双击start.exe无反应，使用管理员身份打开也无反应。

**Comment by jasonjshi** [comment]
同问，提示无法执行script ngui

**Comment by blackboxo** [comment]
是直接下载的压缩包吗

**Comment by foredoom007** [comment]
是的，下载压缩包的时候浏览器甚至弹窗阻止了下载，一直点保留下载到电脑上，解压缩后的.exe文件点击就没有反应了。
