### ISSUE TITLE
【UI】在win11当中打开的界面太小了，不便于观看

### ISSUE THREAD

**Issue by leftttt** [blackboxo/CleanMyWechat#62]
- 而且有些好奇为什么没有最小化按钮

**Comment by blackboxo** [comment]
当时没做 Win11 的测试，可能有点问题

**Comment by Toby-Shi-cloud** [comment]
我的win11看起来很正常。大小是460*427左右，感觉很合适。而且大小是会随着显示设置中的缩放变化的。可能是你的分辨率过高之类的原因？
