### ISSUE TITLE
win11闪退

### ISSUE THREAD

**Issue by mervynlam** [blackboxo/CleanMyWechat#64]
旧版是打开设置就闪退，下载新版后是打开后一段时间，怀疑也是自动打开设置页面时闪退了。

**Comment by blackboxo** [comment]
神奇，是不允许创建文件导致的么？

**Comment by mervynlam** [comment]
> 神奇，是不允许创建文件导致的么？

醍醐灌顶，确实是这样的，换了个地方就好了，谢谢
