### ISSUE TITLE
最近的版本貌似不好使了（包括395）

### ISSUE THREAD

**Issue by fufubrightman** [blackboxo/CleanMyWechat#65]
已经选择到了微信内手动设置的数据文件夹，也识别到了相应的微信账号，但是全勾上的情况下还是提示没有可清理的文件不知道是不是因为微信数据架构更改了？还是我操作有问题吗？呜呜呜清理不了心里好不踏实

**Comment by blackboxo** [comment]
有下载最新版本么？

**Comment by blackboxo** [comment]
日期的设置是不是太久了呢

**Comment by fufubrightman** [comment]
> 日期的设置是不是太久了呢

![image](https://github.com/blackboxo/CleanMyWechat/assets/92922274/4c89b932-9b37-4d64-a002-209c9a77c99c)
一直设置的是350天左右，之前都是正常清理的呜呜呜

**Comment by blackboxo** [comment]
你这个微信账号看着不太对，desktop.ini ?

**Comment by fufubrightman** [comment]
> 你这个微信账号看着不太对，desktop.ini ?

啊对，一直是这样，就是下拉列表里确实是有我登录的两个微信号，也能逐一更改对应微信号的清理选项，但是保存后立马点进设置，又会默认显示desktop.ini，另外，我昨晚试着把344天改成233天，就又能识别垃圾了，但两次识别出来的东西貌似不太一样，一次是连带很多文件夹（例如2022-04格式的文件夹）一起删了，我觉得不太对，从回收站还原之后又扫，扫出来一个文件夹都没有，全是独立的文件😹😹😹😹

**Comment by blackboxo** [comment]
每个账号是独立管理的，需要切换进行设置。

**Comment by blackboxo** [comment]
默认确实是会显示第一个账号，但这个账号应该是误识别了，不过不影响使用。
关于识别的内容，理论上应该是一样的，会包含文件夹和独立文件，只要满足日期条件的都会删除。

**Comment by fufubrightman** [comment]
> 默认确实是会显示第一个账号，但这个账号应该是误识别了，不过不影响使用。 关于识别的内容，理论上应该是一样的，会包含文件夹和独立文件，只要满足日期条件的都会删除。

误识别这个的话，我倒是不太特别在意，只要可以正常清理指定日期以外的垃圾文件和图片就可以了，至于误识别，我猜想可能是因为我在微信设置里手动修改了数据文件夹的存放位置？🤔

**Comment by blackboxo** [comment]
只要账号是正确的，存放路径就是正确的

**Comment by fufubrightman** [comment]
> 只要账号是正确的，存放路径就是正确的

嗯呐，谢谢大佬啦❤️❤️
