### ISSUE TITLE
能否支持针对不同聊天会话的清理？

### ISSUE THREAD

**Issue by IcyChlorine** [blackboxo/CleanMyWechat#68]
希望能支持**针对不同聊天会话的清理**，例如，保留特定聊天会话中的图片和文件。

之前将文件传输助手用作临时图片储存器了，存储了很多重要的截图。希望能在清理其它聊天会话过时内容的同时保留文件传输助手中的内容:-)

**Comment by blackboxo** [comment]
这个微信自带的功能应该就可以处理，我无法解析特定聊天对话
