### ISSUE TITLE
需求描述文件 `requirements.txt` 需要更新

### ISSUE THREAD

**Issue by muziing** [blackboxo/CleanMyWechat#70]
目前的需求文件中，关于 PyQt5 依赖项的要求是强制版本为 5.13.0，然而这个发布于 2019 年 7 月的版本在许多 PyPI 源中已经被删除，导致安装错误。建议更新为 `PyQt5>=5.13.0` 或 `PyQt5~=5.15.0`。

另外，由于此项目主要面向国内用户，也可以考虑将强制使用国内PyPI镜像源写入需求文件。

建议修改示意：

```text
--index-url https://pypi.tuna.tsinghua.edu.cn/simple

Send2Trash~=1.5.0
PyQt5>=5.13.0
python_dateutil~=2.7.5
```

关于 requirements.txt 中的版本约束语法，可以参考[这里](https://muzing.top/posts/594ac4a6/#%E7%89%88%E6%9C%AC%E7%BA%A6%E6%9D%9F%E7%AC%A6)。

**Comment by blackboxo** [comment]
Great！ Please create a pull request
