### ISSUE TITLE
提示信息过长，无法完整显示

### ISSUE THREAD

**Issue by how2051** [blackboxo/CleanMyWechat#84]
![1719726015376](https://github.com/blackboxo/CleanMyWechat/assets/55384174/80264941-ff2c-4115-8b29-51218a636101)

**Comment by how2051** [comment]
在 [e6b9a9a8de745d216b012a8a7038451c1c015c06] 这笔 patch 中已修复，已提PR，等待合入。
修复后的效果：
![1719726062460](https://github.com/blackboxo/CleanMyWechat/assets/55384174/d5c08c9a-4317-4d5e-8ff6-fc4959006d71)

**Comment by blackboxo** [comment]
merged, thanks
